### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rubensworks** [rdfostrich/article-swj2020-cobra#3]
@RubenVerborgh could you review this article for Semantic Web Journal (permanent call on full papers)?

The print view needs some polishing, but I'll do that once the text needs no more changes.

**Comment by RubenVerborgh** [comment]
Working on this at https://github.com/rdfostrich/article-swj2020-cobra/tree/reviews/rv

**Comment by rubensworks** [comment]
Resolved the first round of comments in b77959ac94ced6153d022b344d399d0b4f4ba63f, so this should be good to for round 2.

**Comment by RubenVerborgh** [comment]
Happy new year, and my apologies for the extreme delay. Done in e3c151d45dc3823a570fb39164746aad6fba261b.
